const {
  AllianceApi,
  AssetsApi,
  BookmarksApi,
  CalendarApi,
  CharacterApi,
  ClonesApi,
  ClonesApi,
  ContactsApi,
  ContractsApi,
  CorporationApi,
  DogmaApi,
  FactionWarfareApi,
  FittingsApi,
  FleetsApi,
  IncursionsApi,
  IndustryApi,
  InsuranceApi,
  KillmailsApi,
} = require("eve_swagger_interface");

module.exports = {
  AllianceApi,
  AssetsApi,
  BookmarksApi,
  CalendarApi,
  CharacterApi,
  ClonesApi,
  ContactsApi,
  ContractsApi,
  CorporationApi,
  DogmaApi,
  FactionWarfareApi,
  FittingsApi,
  FleetsApi,
  IncursionsApi,
  IndustryApi,
  InsuranceApi,
  KillmailsApi,
};
